version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network 
  app:
    container_name: docker-node-mongo
    restart: always
    ports:
      - "8080:8080"
    build: .
    volumes:
      - .:/usr/src/app
    external_links:
      - mongo
    command: npm run devStart
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
