version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    env_file: .env
    networks:
      - app-network 
  app:
    container_name: docker-node-mongo
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    external_links:
      - mongo
    env_file: .env
    environment:
      - MONGO_URI=mongodb://${MONGO_DATABASE_USERNAME}:${MONGO_DATABASE_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
