#!/bin/sh
# Put this in /etc/cron.daily
BACKUP_DIR_SRC=/var/backups/mongobackups
BACKUP_SERVER_IP=178.128.12.5
BACKUP_SERVER_DIR_DEST=/home/kelly/mongo-block-backup

current_time=$(date "+%Y.%m.%d-%H.%M.%S")


docker exec -ti mongo sh -c 'rm -r /data_con*'
docker exec -ti mongo mkdir data_con_$current_time -p
docker exec -ti mongo mongodump --out /data_con_$current_time

mkdir -p $BACKUP_DIR_SRC  
docker cp mongo:/data_con_$current_time/   $BACKUP_DIR_SRC  	# copy backup directory to local machine

rsync -r $BACKUP_DIR_SRC/*  kelly@$BACKUP_SERVER_IP:$BACKUP_SERVER_DIR_DEST	# use rsync to transfer fiels to backup server


rm -rf $BACKUP_DIR_SRC/*	# remove backups from local machine, now that they're stored
